# Generated by Django 4.2.6 on 2023-11-03 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("504d2a5e-b109-4bbb-b694-ec442175271c"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
