# Generated by Django 4.2.6 on 2023-11-03 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3a6b39b0-aae9-47e9-a46b-84460e21b2d5"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
