# Generated by Django 4.2.6 on 2023-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
